backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "products"
    label: "Товары"
    folder: "content/products"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - {label: "Название товара", name: "title", widget: "string"}
      - {label: "Цена (в рублях)", name: "price", widget: "number"}
      - label: "Категории (можно выбрать несколько)"
        name: "gender"
        widget: "select"
        multiple: true
        options: ["женское", "мужское", "девочки", "мальчики", "унисекс"]
      - label: "Типы одежды (можно выбрать несколько)"
        name: "type"
        widget: "select"
        multiple: true
        options: ["футболки", "штаны", "шорты", "платья", "рубашки", "верхняя одежда", "обувь", "аксессуары"]
      - {label: "Описание", name: "description", widget: "text", required: false}
      - {label: "Главная фотография", name: "image", widget: "image"}
      - label: "Дополнительные фотографии"
        name: "images"
        widget: "list"
        required: false
        field: {label: "Фото", name: "img", widget: "image"}
