backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products_file"
    label: "Товары"
    files:
      - name: "all_products"
        label: "Список всех товаров"
        file: "content/products/index.json"
        fields:
          - label: "Товары"
            name: "products"
            widget: "list"
            fields:
              - { label: "Название товара", name: "title", widget: "string" }
              - { label: "Пол / Возраст", name: "gender", widget: "select", options: ["женское", "мужское", "девочка", "мальчик"] }
              - { label: "Категория", name: "type", widget: "select", options: ["верх", "низ", "обувь"] }
              - { label: "Цена (только цифры)", name: "price", widget: "number" }
              - { label: "Фотография товара", name: "image", widget: "image" }
